language: python
python:
  - "3.6"
cache:
  - pandoc
  - texlive-latex-base
  - texlive-latex-extra
install:
  - pip install panflute
env:
  global:
  - USER="Nauja"
  - EMAIL="TravisCI@mail.com"
  - REPO="Entropy"
  - FILES="pdf/Draft.pdf"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  - secure: "Trs5Ba8X6qSHujuNyUXZA2QAWBuh61muXBslKF/DMrYXhHdws0Kbg0c8T8oL572CgLiBAtXBnrwTjjwuY8MHw+6uBtHaqrrldG8VtAKKGhJ+RzsdJDtMGr2elsmcLryNxntAQlZ2aKLctK5j5YiOV8e8fcOOeDwqqlVpXAUN0ie9hr8EMe0FjS0rJUggp9WZJBxiM57JY6hV6beO/DUyGkSSIxGfkk8sjIO/GxeVNAx7/wom/4m1SzGuorh9CMnYD8x7MST4Bn+opQP4CbFv50fLKsJPi8Ptg40y2bDpO84pg2KmNTt2MPIYiIFl0WoRIX+ntYIRNxSeHmYDzOV5LXltj5mFrd12oTYuEpzggY17RK8OytneZ3BgD8gLQspZHMuXq1hn2kmbHkAg7zGEjS/Oxbdcp6eIKfTkknMykg43DWWmE7zARrZb3qdugsCizUoYibYoRBTzGR64qjjVa/okvQTehUdCRL+DuswoY5yXCUFC+vK9kXysiH0XriFIvwMBZWMp7ccxjg26eWLzLFc1N95vzxpcLuk9BpgsVmmq2vFWxT77Lkc5Fl82zHFZUq+p1Fsnb+ihMqgCz8yVW501farxD9cCDEiqyaMb2Inqa1LfSnCVh4Lg9Dr+PKJrYlgJBjnKzIsImRMfA3wcR5MZQ/S8CivpfHP7Aidtkjo="
before_script:
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-fonts-extra
  - sudo apt-get install texlive-latex-extra
  - curl -L https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb > ./pandoc.deb
  - sudo dpkg -i ./pandoc.deb
script:
    # Test install with current version of setuptools
  - make Draft.pdf
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f pdf/Draft.pdf Draft.pdf
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1