language: python
python:
  - "3.6"
cache:
  - pandoc
  - texlive-latex-base
  - texlive-latex-extra
install:
  - pip install panflute
env:
  global:
  - USER="Nauja"
  - EMAIL="travis@travis-ci.org"
  - GH_REPO="github.com/Nauja/Entropy.git"
before_script:
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-fonts-extra
  - sudo apt-get install texlive-latex-extra
  - curl -L https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb > ./pandoc.deb
  - sudo dpkg -i ./pandoc.deb
script:
    # Test install with current version of setuptools
  - make Draft.pdf
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git remote
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${USER}
  - git commit -a -m "Travis commit"
  - git push "https://Nauja:${SECURE_TOKEN}@${GH_REPO}" master